version: "3.8"
services:
  postgres-db:
    image: bdbt-postgres:1.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  bdbt_site:
    image: bdbt-app-image:1.0
    ports:
      - 5001:5000
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres-db:5432/postgres
    depends_on:
      - postgres-db

volumes:
  pgdata: